package com.fundflow.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "PAYMENT")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PAYMENT_ID")
    private Long id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DONATION_ID", nullable = false, unique = true)
    private Donation donation;

    /** e.g. MOCK_CARD, MOCK_UPI - method names stay generic so a real gateway can slot in later. */
    @Column(name = "METHOD", nullable = false, length = 30)
    private String method;

    @Enumerated(EnumType.STRING)
    @Column(name = "STATUS", nullable = false, length = 20)
    @Builder.Default
    private TxnStatus status = TxnStatus.PENDING;

    /** Fake reference id generated by MockPaymentService, stands in for a real gateway payment id. */
    @Column(name = "MOCK_REFERENCE", length = 100)
    private String mockReference;

    @Column(name = "PAID_AT")
    private LocalDateTime paidAt;

    @Column(name = "CREATED_AT", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }
}
