-- ============================================================
-- FundFlow - Oracle Database Schema
-- Run this once against your Oracle XE service (e.g. XEPDB1)
-- as the fundflow_user schema owner.
-- Assumes Oracle 12c+ (uses GENERATED AS IDENTITY, no manual sequences/triggers needed).
-- NOTE: table is named APP_USER, not USER, because USER is a reserved
-- pseudo-column/keyword in Oracle.
-- ============================================================

CREATE TABLE ROLE (
    ROLE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_NAME   VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE APP_USER (
    USER_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FULL_NAME     VARCHAR2(150) NOT NULL,
    EMAIL         VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE_ID       NUMBER NOT NULL,
    ENABLED       NUMBER(1) DEFAULT 1 NOT NULL CHECK (ENABLED IN (0,1)),
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID)
);

CREATE TABLE CAMPAIGN (
    CAMPAIGN_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE             VARCHAR2(200) NOT NULL,
    DESCRIPTION       CLOB NOT NULL,
    CATEGORY          VARCHAR2(50),
    TARGET_AMOUNT     NUMBER(12,2) NOT NULL CHECK (TARGET_AMOUNT > 0),
    CURRENT_AMOUNT    NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (CURRENT_AMOUNT >= 0),
    START_DATE        DATE NOT NULL,
    END_DATE          DATE NOT NULL,
    ORGANIZER_ID      NUMBER NOT NULL,
    BENEFICIARY_NAME  VARCHAR2(150) NOT NULL,
    BENEFICIARY_INFO  VARCHAR2(1000),
    IMAGE_PATH        VARCHAR2(300), -- local asset path, e.g. /assets/images/campaign-placeholder-1.png
    STATUS            VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL
                       CHECK (STATUS IN ('DRAFT','PENDING','APPROVED','REJECTED','BLOCKED','COMPLETED')),
    REVIEW_NOTES      VARCHAR2(1000), -- admin's reason on reject/block
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CAMPAIGN_ORGANIZER FOREIGN KEY (ORGANIZER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT CHK_CAMPAIGN_DATES CHECK (END_DATE > START_DATE)
);

CREATE TABLE CAMPAIGN_DOCUMENT (
    DOCUMENT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CAMPAIGN_ID    NUMBER NOT NULL,
    DOCUMENT_NAME  VARCHAR2(200) NOT NULL,
    DOCUMENT_PATH  VARCHAR2(300) NOT NULL,
    UPLOADED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DOC_CAMPAIGN FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN (CAMPAIGN_ID) ON DELETE CASCADE
);

CREATE TABLE DONATION (
    DONATION_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CAMPAIGN_ID   NUMBER NOT NULL,
    DONOR_ID      NUMBER NOT NULL,
    AMOUNT        NUMBER(12,2) NOT NULL CHECK (AMOUNT > 0),
    STATUS        VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
                  CHECK (STATUS IN ('PENDING','SUCCESS','FAILED')),
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DONATION_CAMPAIGN FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN (CAMPAIGN_ID),
    CONSTRAINT FK_DONATION_DONOR FOREIGN KEY (DONOR_ID) REFERENCES APP_USER (USER_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DONATION_ID     NUMBER NOT NULL UNIQUE,
    METHOD          VARCHAR2(30) NOT NULL, -- e.g. MOCK_CARD, MOCK_UPI
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
                    CHECK (STATUS IN ('PENDING','SUCCESS','FAILED')),
    MOCK_REFERENCE  VARCHAR2(100), -- fake reference id, stands in for a real gateway ref
    PAID_AT         TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PAYMENT_DONATION FOREIGN KEY (DONATION_ID) REFERENCES DONATION (DONATION_ID)
);

CREATE TABLE TRANSACTION_LOG (
    TRANSACTION_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PAYMENT_ID       NUMBER NOT NULL,
    TRANSACTION_REF  VARCHAR2(100) NOT NULL UNIQUE,
    AMOUNT           NUMBER(12,2) NOT NULL,
    STATUS           VARCHAR2(20) NOT NULL
                     CHECK (STATUS IN ('PENDING','SUCCESS','FAILED')),
    CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_TXN_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
);

CREATE TABLE NOTIFICATION (
    NOTIFICATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    MESSAGE         VARCHAR2(500) NOT NULL,
    TYPE            VARCHAR2(50) NOT NULL, -- e.g. DONATION_SUCCESS, CAMPAIGN_APPROVED
    IS_READ         NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_READ IN (0,1)),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID)
);

CREATE TABLE CAMPAIGN_UPDATE (
    UPDATE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CAMPAIGN_ID   NUMBER NOT NULL,
    ORGANIZER_ID  NUMBER NOT NULL,
    UPDATE_TEXT   VARCHAR2(2000) NOT NULL,
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_UPDATE_CAMPAIGN FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN (CAMPAIGN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UPDATE_ORGANIZER FOREIGN KEY (ORGANIZER_ID) REFERENCES APP_USER (USER_ID)
);

CREATE TABLE SAVED_CAMPAIGN (
    SAVED_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DONOR_ID      NUMBER NOT NULL,
    CAMPAIGN_ID   NUMBER NOT NULL,
    SAVED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SAVED_DONOR FOREIGN KEY (DONOR_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT FK_SAVED_CAMPAIGN FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN (CAMPAIGN_ID),
    CONSTRAINT UQ_SAVED_DONOR_CAMPAIGN UNIQUE (DONOR_ID, CAMPAIGN_ID)
);

-- ---- Useful indexes ----
CREATE INDEX IDX_CAMPAIGN_STATUS ON CAMPAIGN (STATUS);
CREATE INDEX IDX_CAMPAIGN_ORGANIZER ON CAMPAIGN (ORGANIZER_ID);
CREATE INDEX IDX_DONATION_CAMPAIGN ON DONATION (CAMPAIGN_ID);
CREATE INDEX IDX_DONATION_DONOR ON DONATION (DONOR_ID);
CREATE INDEX IDX_NOTIFICATION_USER ON NOTIFICATION (USER_ID);

-- ---- Seed roles ----
INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_DONOR');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_ORGANIZER');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');
COMMIT;
